# drone.io v0.4
# armhf

build:
    image: takawang/dind:$$arch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    commands:
        - docker build --no-cache=true -t edgepro/c-modbus-slave:$$arch -f Dockerfile.$$arch .
        - docker run -itd --name=slave edgepro/c-modbus-slave:$$arch
        - docker logs slave
        - docker rm -f slave
        - docker push edgepro/c-modbus-slave:$$arch

matrix:
    arch:
        - armhf

